if empty(glob('~/.vim/colors/monokai.vim'))
  silent !curl -fLo ~/.vim/colors/monokai.vim --create-dirs
    \ https://raw.githubusercontent.com/sickill/vim-monokai/master/colors/monokai.vim
endif
if empty(glob('~/.vim/colors/cake.vim'))
  silent !curl -fLo ~/.vim/colors/cake.vim --create-dirs
	\ https://raw.githubusercontent.com/GGalizzi/cake-vim/master/colors/cake.vim
endif
colorscheme cake

set tabstop=4									" who came up with 8?
set shiftwidth=4								" i know right?
set number										" show line numbers
set relativenumber								" make line numbers relative
set cursorline									" highlight current line
set wildmenu									" visual autocomplete for cmd
set lazyredraw									" speed up macros
set showmatch									" highlight [{()}]
set ignorecase									" search is case insensitive
set smartcase									" only lower case searches are case insensitive
set showcmd										" show cmd bottom right
set list										" show hidden chars
set backupdir=~/.vim/backup//,.					" do not clutter working directory
set directory=~/.vim/backup//,.					" do not clutter working directory

" plugins installed with vim-plug
" https://github.com/junegunn/vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'ctrlpvim/ctrlp.vim'
Plug 'tpope/vim-sensible'
call plug#end()

" remap leader to space
let mapleader = ' '
" nerdtree
nnoremap <leader>t :NERDTreeToggle<CR>
" the silver surfer
nnoremap <leader>a :Ag 
" jk works as esc
inoremap jk <esc>
" remap command key
nnoremap ; :
