shopt -s checkwinsize
bind "set completion-ignore-case on"
bind "set show-all-if-ambiguous on"

source ~/git/dotfiles/sh/env.sh
source ~/git/dotfiles/sh/aliases.sh
source ~/git/dotfiles/sh/functions.sh

set -o vi
